name: frontend_home_assignment
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  auto_route: ^5.0.4
  flutter_riverpod: ^2.1.3
  flutter_screenutil: ^5.6.0
  freezed: ^2.3.2
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  bloc: ^8.1.0
  get_it: ^7.2.0
  intl: ^0.18.0
  dio: ^5.0.0
  retrofit: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  auto_route_generator: ^5.0.3
  build_runner: ^2.3.3
  json_serializable: ^6.5.4
  retrofit_generator: '>=5.0.0 <6.0.0'


flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
  #   - images/a_dot_ham.jpeg

